module.exports = [
  { Number: "1",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "2",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "3",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "4",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "5",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "6",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "7",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "8",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  { Number: "9",
    active: false,
    src: "./images/cursor_icon.jpg",
  },
  ]